version: "3.9"
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: eventadmin
      POSTGRES_PASSWORD: eventpass
      POSTGRES_DB: eventdb
    ports:
      - "5432:5432"
    # volumes:
    #   - db-data:/var/lib/postgresql/data

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://eventadmin:eventpass@db:5432/eventdb
      JWT_SECRET: supersecretkey
    ports:
      - "5000:5000"
    # No volumes for backend in production build!

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app

# volumes:
#   db-data: 